# Sources Configuration
# type: rss | scrape | telegram
# engine (for scrape): beautifulsoup | playwright
# language: ISO 639-1 code

regions:
  iran:
    label: "Iran"
    sources:
      - name: "IRNA"
        type: rss
        language: fa
        url: "https://www.irna.ir/rss"
        category: state

      - name: "Tasnim News"
        type: rss
        language: fa
        url: "https://www.tasnimnews.com/fa/rss/most-visited"
        category: state

      - name: "Fars News"
        type: rss
        language: fa
        url: "https://www.farsnews.ir/rss"
        category: state

      - name: "Press TV"
        type: rss
        language: en
        url: "https://www.presstv.ir/rss.xml"
        category: state
        skip_translation: true

      - name: "Tasnim News English"
        type: rss
        language: en
        url: "https://www.tasnimnews.com/en/rss/"
        category: state
        skip_translation: true

      - name: "Mehr News Agency"
        type: rss
        language: en
        url: "https://en.mehrnews.com/rss"
        category: state
        skip_translation: true

      - name: "Al Alam"
        type: rss
        language: ar
        url: "https://www.alalam.ir/rss/important_news"
        category: state

      - name: "Tehran Times"
        type: rss
        language: en
        url: "https://www.tehrantimes.com/rss"
        category: state
        skip_translation: true

      - name: "Iran News Daily"
        type: rss
        language: en
        url: "https://irannewsdaily.com/feed/"
        category: independent
        skip_translation: true

      - name: "Iran Herald"
        type: rss
        language: en
        url: "https://feeds.iranherald.com/rss/1b76a2b4cf7810bd"
        category: independent
        skip_translation: true

      # ── Telegram channels ──

      - name: "Press TV (TG)"
        type: telegram
        channel: "PressTV"
        language: en
        category: state
        skip_translation: true

      - name: "Iran International English (TG)"
        type: telegram
        channel: "iranintl_en"
        language: en
        category: independent
        skip_translation: true

  russia:
    label: "Russia"
    sources:
      - name: "TASS"
        type: rss
        language: ru
        url: "https://tass.ru/rss/v2.xml"
        category: state

      - name: "RIA Novosti"
        type: rss
        language: ru
        url: "https://ria.ru/export/rss2/archive/index.xml"
        category: state

      - name: "RT"
        type: rss
        language: en
        url: "https://www.rt.com/rss/news/"
        category: state
        skip_translation: true

      - name: "Sputnik"
        type: rss
        language: en
        url: "https://sputnikglobe.com/export/rss2/archive/index.xml"
        category: state
        skip_translation: true

      - name: "Kommersant"
        type: rss
        language: ru
        url: "https://www.kommersant.ru/RSS/news.xml"
        category: independent

      - name: "RBC"
        type: rss
        language: ru
        url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss"
        category: independent

      # ── Telegram channels ──

      - name: "RT Official (TG)"
        type: telegram
        channel: "rt_com"
        language: en
        category: state
        skip_translation: true

      - name: "Sputnik International (TG)"
        type: telegram
        channel: "SputnikInt"
        language: en
        category: state
        skip_translation: true

      - name: "Russian MoD English (TG)"
        type: telegram
        channel: "mod_russia_en"
        language: en
        category: state
        skip_translation: true

      - name: "Rybar (TG)"
        type: telegram
        channel: "rybar"
        language: ru
        category: state-aligned

      - name: "Rybar English (TG)"
        type: telegram
        channel: "ryaborenglish"
        language: en
        category: state-aligned
        skip_translation: true

      - name: "SouthFront English (TG)"
        type: telegram
        channel: "SouthFrontEnglish"
        language: en
        category: state-aligned
        skip_translation: true

      - name: "Conflict Intelligence Team (TG)"
        type: telegram
        channel: "CIG_telegram"
        language: en
        category: independent
        skip_translation: true

  israel:
    label: "Israel"
    sources:
      - name: "Ynet"
        type: rss
        language: he
        url: "https://www.ynet.co.il/Integration/StoryRss2.xml"
        category: state-aligned

      - name: "Maariv"
        type: rss
        language: he
        url: "https://www.maariv.co.il/Rss/RssChad498"
        category: state-aligned

      - name: "Jerusalem Post"
        type: rss
        language: en
        url: "https://www.jpost.com/rss/rssfeedsfrontpage.aspx"
        category: independent
        skip_translation: true

  gulf:
    label: "Gulf States"
    sources:
      - name: "QNA Qatar (Arabic)"
        type: rss
        language: ar
        url: "https://qna.org.qa/ar-QA/Pages/RSS-Feeds/Qatar"
        category: state

      - name: "QNA General (Arabic)"
        type: rss
        language: ar
        url: "https://qna.org.qa/ar-QA/Pages/RSS-Feeds/General"
        category: state

      - name: "BNA (Bahrain)"
        type: rss
        language: ar
        url: "https://www.bna.bh/GenerateRssFeed.aspx?categoryId=155"
        category: state

      - name: "Al Arabiya"
        type: rss
        language: ar
        url: "https://www.alarabiya.net/feed/rss2/ar.xml"
        category: state-aligned

      - name: "SPA Arabic (Saudi)"
        type: rss
        language: ar
        url: "https://www.spa.gov.sa/rss.xml"
        category: state

      - name: "SPA English (Saudi)"
        type: rss
        language: en
        url: "https://www.spa.gov.sa/en/rss.xml"
        category: state
        skip_translation: true

      - name: "WAM Arabic (UAE)"
        type: rss
        language: ar
        url: "https://www.wam.ae/ar/rss/all"
        category: state

      - name: "WAM English (UAE)"
        type: rss
        language: en
        url: "https://www.wam.ae/en/rss/all"
        category: state
        skip_translation: true

      - name: "QNA Qatar (English)"
        type: rss
        language: en
        url: "https://qna.org.qa/en/Pages/RSS-Feeds/Qatar"
        category: state
        skip_translation: true

      - name: "QNA General (English)"
        type: rss
        language: en
        url: "https://qna.org.qa/en/Pages/RSS-Feeds/General"
        category: state
        skip_translation: true

      - name: "ONA (Oman)"
        type: rss
        language: en
        url: "https://omannews.gov.om/rss/news"
        category: state
        skip_translation: true

      - name: "BNA English (Bahrain)"
        type: rss
        language: en
        url: "https://www.bna.bh/en/RSSFeeds.aspx"
        category: state
        skip_translation: true

      - name: "KUNA (Kuwait)"
        type: rss
        language: en
        url: "https://www.kuna.net.kw/RSS.aspx?language=en"
        category: state
        skip_translation: true

      - name: "Al Jazeera English"
        type: rss
        language: en
        url: "https://www.aljazeera.com/xml/rss/all.xml"
        category: state
        skip_translation: true

      - name: "Al Jazeera Arabic"
        type: rss
        language: ar
        url: "https://www.aljazeera.net/feed"
        category: state

      - name: "Asharq Al-Awsat"
        type: rss
        language: en
        url: "https://english.aawsat.com/feed"
        category: state-aligned
        skip_translation: true

      - name: "WAM English (TG)"
        type: telegram
        channel: "wamnews_en"
        language: en
        category: state
        skip_translation: true

  middle_east:
    label: "Middle East (Independent)"
    sources:
      - name: "Middle East Monitor"
        type: rss
        language: en
        url: "https://www.middleeastmonitor.com/feed/"
        category: independent
        skip_translation: true

      - name: "Middle East Eye"
        type: rss
        language: en
        url: "https://www.middleeasteye.net/rss"
        category: independent
        skip_translation: true

      - name: "Al-Monitor"
        type: rss
        language: en
        url: "https://www.al-monitor.com/rss"
        category: independent
        skip_translation: true

      - name: "The New Arab"
        type: rss
        language: en
        url: "https://www.newarab.com/rss"
        category: independent
        skip_translation: true

      - name: "SANA Syria"
        type: rss
        language: en
        url: "https://sana.sy/en/?feed=rss2"
        category: state
        skip_translation: true

      - name: "Jordan Times"
        type: rss
        language: en
        url: "https://www.jordantimes.com/feed"
        category: state-aligned
        skip_translation: true

      - name: "Daily News Egypt"
        type: rss
        language: en
        url: "https://www.dailynewsegypt.com/feed/"
        category: independent
        skip_translation: true

      - name: "Iraq Business News"
        type: rss
        language: en
        url: "https://www.iraq-businessnews.com/feed/"
        category: independent
        skip_translation: true

      # ── Telegram channels ──

      - name: "Abu Ali Express (TG)"
        type: telegram
        channel: "AbuAliEnglish"
        language: en
        category: independent
        skip_translation: true

      - name: "War Monitors (TG)"
        type: telegram
        channel: "warmonitors"
        language: en
        category: independent
        skip_translation: true

      - name: "Military OSINT (TG)"
        type: telegram
        channel: "military_osint"
        language: en
        category: independent
        skip_translation: true

      - name: "Al Mayadeen News (TG)"
        type: telegram
        channel: "AlMayadeenNews"
        language: ar
        category: state-aligned

  proxies:
    label: "Proxy Actors"
    sources:
      - name: "Al Manar (Hezbollah)"
        type: rss
        language: ar
        url: "https://www.almanar.com.lb/rss.php"
        category: proxy

      - name: "Al Manar English (Hezbollah)"
        type: rss
        language: en
        url: "https://www.almanar.com.lb/english/rss.php"
        category: proxy
        skip_translation: true

      - name: "Al Ahed News (Hezbollah)"
        type: rss
        language: ar
        url: "https://www.alahednews.com.lb/arabic/rss"
        category: proxy

      - name: "Al Ahed News English (Hezbollah)"
        type: rss
        language: en
        url: "https://www.alahednews.com.lb/english/rss"
        category: proxy
        skip_translation: true

      - name: "Islamic Resistance"
        type: rss
        language: ar
        url: "https://moqawama.org/rss.php"
        category: proxy

      - name: "Al Masirah (Houthis)"
        type: rss
        language: ar
        url: "https://www.almasirah.net.ye/rss/"
        category: proxy

      - name: "SABA News Arabic (Houthis)"
        type: rss
        language: ar
        url: "https://www.saba.ye/ar/rss.php"
        category: proxy

      - name: "SABA News English (Houthis)"
        type: rss
        language: en
        url: "https://www.saba.ye/en/rss.php"
        category: proxy
        skip_translation: true

      - name: "Ansarollah Official"
        type: rss
        language: ar
        url: "https://ansarollah.com.ye/feed/"
        category: proxy

      - name: "Hamas (Palestine Info)"
        type: rss
        language: en
        url: "https://www.palinfo.com/rss"
        category: proxy
        skip_translation: true

      - name: "Al-Mayadeen English"
        type: rss
        language: en
        url: "https://english.almayadeen.net/rss"
        category: proxy
        skip_translation: true

      # ── Telegram channels ──
      # Only channels with public web preview (t.me/s/) work without a Bot API token.
      # @C_Media_h, @M_Media_Y, @Qassam_English have preview disabled —
      # to enable them, upgrade to Telethon (see README) and uncomment below.

      - name: "Islamic Resistance Iraq (TG)"
        type: telegram
        channel: "Saberin_News"
        language: ar
        category: proxy

      - name: "Resistance News (TG)"
        type: telegram
        channel: "resistance_12"
        language: ar
        category: proxy

      # - name: "Hezbollah Military Media (TG)"
      #   type: telegram
      #   channel: "C_Media_h"
      #   language: ar
      #   category: proxy

      # - name: "Houthi Military Media (TG)"
      #   type: telegram
      #   channel: "M_Media_Y"
      #   language: ar
      #   category: proxy

      # - name: "Hamas Qassam Brigades (TG)"
      #   type: telegram
      #   channel: "Qassam_English"
      #   language: en
      #   category: proxy
      #   skip_translation: true

  china:
    label: "China"
    sources:
      - name: "Xinhua English"
        type: rss
        language: en
        url: "http://www.xinhuanet.com/english/rss/worldrss.xml"
        category: state
        skip_translation: true

      - name: "Global Times"
        type: rss
        language: en
        url: "https://www.globaltimes.cn/rss/outbrain.xml"
        category: state-aligned
        skip_translation: true

      - name: "CGTN World"
        type: rss
        language: en
        url: "https://www.cgtn.com/subscribe/rss/section/world.xml"
        category: state
        skip_translation: true

      - name: "China Daily World"
        type: rss
        language: en
        url: "https://www.chinadaily.com.cn/rss/world_rss.xml"
        category: state
        skip_translation: true

      - name: "South China Morning Post"
        type: rss
        language: en
        url: "https://www.scmp.com/rss/91/feed"
        category: independent
        skip_translation: true

  turkey:
    label: "Turkey"
    sources:
      - name: "Anadolu Agency"
        type: rss
        language: en
        url: "https://www.aa.com.tr/en/rss/default?cat=world"
        category: state
        skip_translation: true

      - name: "Daily Sabah World"
        type: rss
        language: en
        url: "https://www.dailysabah.com/rssFeed/world"
        category: state-aligned
        skip_translation: true

  south_asia:
    label: "South Asia"
    sources:
      - name: "Dawn (Pakistan)"
        type: rss
        language: en
        url: "https://www.dawn.com/feeds/home"
        category: independent
        skip_translation: true

      - name: "Geo TV (Pakistan)"
        type: rss
        language: en
        url: "https://www.geo.tv/rss/1/1"
        category: independent
        skip_translation: true

      - name: "The News International (Pakistan)"
        type: rss
        language: en
        url: "https://www.thenews.com.pk/rss/1/1"
        category: independent
        skip_translation: true

      - name: "Express Tribune (Pakistan)"
        type: rss
        language: en
        url: "https://tribune.com.pk/feed/home"
        category: independent
        skip_translation: true

      - name: "The Hindu International"
        type: rss
        language: en
        url: "https://www.thehindu.com/news/international/feeder/default.rss"
        category: independent
        skip_translation: true

      - name: "Times of India World"
        type: rss
        language: en
        url: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms"
        category: independent
        skip_translation: true

      - name: "ThePrint (India)"
        type: rss
        language: en
        url: "https://theprint.in/feed/"
        category: independent
        skip_translation: true

      - name: "Hindustan Times World"
        type: rss
        language: en
        url: "https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml"
        category: independent
        skip_translation: true

  western:
    label: "Western"
    sources:
      - name: "New York Times – Iran"
        type: rss
        language: en
        url: "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/topic/destination/iran/rss.xml"
        category: independent
        skip_translation: true

      - name: "BBC World"
        type: rss
        language: en
        url: "http://news.bbc.co.uk/rss/newsonline_world_edition/feeds.opml"
        category: independent
        skip_translation: true

      - name: "HuffPost World News"
        type: rss
        language: en
        url: "https://www.huffpost.com/section/world-news/feed"
        category: independent
        skip_translation: true

      - name: "NYT Top Stories"
        type: rss
        language: en
        url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
        category: independent
        skip_translation: true

      - name: "FOX News"
        type: rss
        language: en
        url: "http://feeds.foxnews.com/foxnews/latest"
        category: independent
        skip_translation: true

      - name: "Washington Post World"
        type: rss
        language: en
        url: "http://feeds.washingtonpost.com/rss/world"
        category: independent
        skip_translation: true

      - name: "WSJ World News"
        type: rss
        language: en
        url: "https://feeds.a.dj.com/rss/RSSWorldNews.xml"
        category: independent
        skip_translation: true

      - name: "LA Times World & Nation"
        type: rss
        language: en
        url: "https://www.latimes.com/world-nation/rss2.0.xml"
        category: independent
        skip_translation: true

      - name: "CNN International"
        type: rss
        language: en
        url: "http://rss.cnn.com/rss/edition.rss"
        category: independent
        skip_translation: true

      - name: "Yahoo News"
        type: rss
        language: en
        url: "https://news.yahoo.com/rss/mostviewed"
        category: independent
        skip_translation: true

      - name: "CNBC Top News"
        type: rss
        language: en
        url: "https://www.cnbc.com/id/100003114/device/rss/rss.html"
        category: independent
        skip_translation: true

      - name: "Politico Playbook"
        type: rss
        language: en
        url: "https://rss.politico.com/playbook.xml"
        category: independent
        skip_translation: true

      - name: "BBC News"
        type: rss
        language: en
        url: "http://feeds.bbci.co.uk/news/rss.xml"
        category: independent
        skip_translation: true

      - name: "The Guardian World"
        type: rss
        language: en
        url: "https://www.theguardian.com/world/rss"
        category: independent
        skip_translation: true

      - name: "Daily Mail"
        type: rss
        language: en
        url: "https://www.dailymail.co.uk/home/index.rss"
        category: independent
        skip_translation: true

      - name: "The Independent"
        type: rss
        language: en
        url: "http://www.independent.co.uk/news/uk/rss"
        category: independent
        skip_translation: true

      - name: "Daily Express"
        type: rss
        language: en
        url: "http://feeds.feedburner.com/daily-express-news-showbiz"
        category: independent
        skip_translation: true
